# Generated by Django 5.0.2 on 2024-02-29 12:42

import django.db.models.deletion
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='teacher',
            field=models.OneToOneField(limit_choices_to=product.models.teacher_profile_limit_choices_to, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('product', models.ManyToManyField(related_name='products', to='product.product')),
                ('students', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
            },
        ),
    ]
