# Generated by Django 5.0.2 on 2024-02-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_max_students_alter_product_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.RemoveField(
            model_name='studentsgroup',
            name='product',
        ),
        migrations.AddField(
            model_name='studentsgroup',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.product'),
            preserve_default=False,
        ),
    ]
