# Generated by Django 5.0.2 on 2024-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_lesson_name_alter_lesson_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgroup',
            name='current_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
