# Generated by Django 5.0.2 on 2024-03-01 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_studentsgroup_current_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsgroup',
            name='min_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
