# Generated by Django 5.0.2 on 2024-03-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_min_students_studentsgroup_min_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='students',
        ),
    ]
